a = "Ritesh is a good boy\nbut not a bad boy"  #\n  is used to print the next string in a new line
b = "Ritesh is a good boy\tbut not a bad boy"  #\t  is used to print a tab space
c = "Ritesh is a good boy\"but\" not a bad boy"  #\"  is used to print the double quotes in the string
d = "Ritesh is a good boy\\but\\ not a bad boy"  #\\  is used to print a backslash in the string

print(a)
print(b)
print(c)
print(d)