# virtual enviourmnet is used to virtual environment is used to create an isolated Python environment for a project.
#  This allows each project to have its own Python packages and versions without affecting other projects or the system-wide Python installation.
# For example:

# Project A needs:
# Django 4.2
# requests 2.31
# Project B needs:
# Django 5.2
# requests 2.32

# pip freeze > requirment.txt is used for
# pip freeze lists all installed Python packages and their versions.
# > redirects that output into a file named requirements.txt.

