'''

a = int(input("Enter a number: "))
b = 45
c = 56

average = (a+b+c)/3

print(average)

a = int(input("Enter a number: "))
b = int(input("Enter a number: "))
c = int(input("Enter a number: "))

average = (a+b+c)/3

print(average)

'''

# Function definitation
def avg():
    a = int(input("Enter a number: "))
    b = int(input("Enter a number: "))
    c = int(input("Enter a number: "))

    average = (a+b+c)/3

    print(average)

# Function call
avg()
avg()
avg()
avg()
avg()